"""add_categories_and_code_to_immobilisations

Revision ID: a019540d6e7b
Revises: f41c0df6c491
Create Date: 2025-12-25 15:32:30.243888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a019540d6e7b'
down_revision: Union[str, None] = 'f41c0df6c491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('taux_amortissement', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_code'), 'categories', ['code'], unique=True)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.add_column('immobilisations', sa.Column('code', sa.String(length=20), nullable=False))
    op.add_column('immobilisations', sa.Column('categorie_id', sa.Integer(), nullable=True))
    op.add_column('immobilisations', sa.Column('date_mise_en_service', sa.Date(), nullable=True))
    op.add_column('immobilisations', sa.Column('valeur_residuelle', sa.Numeric(precision=15, scale=2), nullable=True))
    op.alter_column('immobilisations', 'libelle',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('immobilisations', 'duree_amortissement',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('immobilisations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('immobilisations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_immobilisations_code'), 'immobilisations', ['code'], unique=True)
    op.create_foreign_key(None, 'immobilisations', 'categories', ['categorie_id'], ['id'])
    op.drop_column('immobilisations', 'motif_sortie')
    op.drop_column('immobilisations', 'compte_comptable')
    op.drop_column('immobilisations', 'date_sortie')
    op.drop_column('immobilisations', 'description')
    op.drop_column('immobilisations', 'mode_amortissement')
    op.alter_column('societes', 'raison_sociale',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('societes', 'adresse',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('societes', 'pays',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('societes', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('societes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('societes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('societes', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('societes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('societes', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('societes', 'pays',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
    op.alter_column('societes', 'adresse',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('societes', 'raison_sociale',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('immobilisations', sa.Column('mode_amortissement', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('immobilisations', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('immobilisations', sa.Column('date_sortie', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('immobilisations', sa.Column('compte_comptable', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('immobilisations', sa.Column('motif_sortie', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'immobilisations', type_='foreignkey')
    op.drop_index(op.f('ix_immobilisations_code'), table_name='immobilisations')
    op.alter_column('immobilisations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('immobilisations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('immobilisations', 'duree_amortissement',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('immobilisations', 'libelle',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('immobilisations', 'valeur_residuelle')
    op.drop_column('immobilisations', 'date_mise_en_service')
    op.drop_column('immobilisations', 'categorie_id')
    op.drop_column('immobilisations', 'code')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_code'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
