"""add_amortissements_table

Revision ID: c87804c3d4e8
Revises: a019540d6e7b
Create Date: 2025-12-25 15:36:13.011473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87804c3d4e8'
down_revision: Union[str, None] = 'a019540d6e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amortissements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('immobilisation_id', sa.Integer(), nullable=False),
    sa.Column('exercice', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('valeur_origine', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('base_amortissable', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('taux', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dotation', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cumul_amortissements', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valeur_nette_comptable', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['immobilisation_id'], ['immobilisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amortissements_id'), 'amortissements', ['id'], unique=False)
    op.add_column('immobilisations', sa.Column('valeur_acquisition', sa.Numeric(precision=15, scale=2), nullable=False))
    op.drop_index(op.f('ix_immobilisations_numero'), table_name='immobilisations')
    op.drop_column('immobilisations', 'numero')
    op.drop_column('immobilisations', 'valeur_origine')
    op.drop_column('immobilisations', 'taux_amortissement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('immobilisations', sa.Column('taux_amortissement', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('immobilisations', sa.Column('valeur_origine', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('immobilisations', sa.Column('numero', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_immobilisations_numero'), 'immobilisations', ['numero'], unique=True)
    op.drop_column('immobilisations', 'valeur_acquisition')
    op.drop_index(op.f('ix_amortissements_id'), table_name='amortissements')
    op.drop_table('amortissements')
    # ### end Alembic commands ###
