"""Initial tables: users, societes, immobilisations

Revision ID: f41c0df6c491
Revises: 
Create Date: 2025-12-25 11:28:43.616280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f41c0df6c491'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('societes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('raison_sociale', sa.String(length=255), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('code_postal', sa.String(length=10), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=3), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siret')
    )
    op.create_index(op.f('ix_societes_code'), 'societes', ['code'], unique=True)
    op.create_index(op.f('ix_societes_id'), 'societes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('immobilisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('societe_id', sa.Integer(), nullable=False),
    sa.Column('compte_comptable', sa.String(length=20), nullable=True),
    sa.Column('date_acquisition', sa.Date(), nullable=False),
    sa.Column('valeur_origine', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('duree_amortissement', sa.Integer(), nullable=True),
    sa.Column('taux_amortissement', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mode_amortissement', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_sortie', sa.Date(), nullable=True),
    sa.Column('motif_sortie', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['societe_id'], ['societes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_immobilisations_id'), 'immobilisations', ['id'], unique=False)
    op.create_index(op.f('ix_immobilisations_numero'), 'immobilisations', ['numero'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_immobilisations_numero'), table_name='immobilisations')
    op.drop_index(op.f('ix_immobilisations_id'), table_name='immobilisations')
    op.drop_table('immobilisations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_societes_id'), table_name='societes')
    op.drop_index(op.f('ix_societes_code'), table_name='societes')
    op.drop_table('societes')
    # ### end Alembic commands ###
